languageCode = "en-us"
title = "rww.science: the blog"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[languages]
[languages.en]
  languageName = "English"
