---
title: Getting to Yes
author: RWW
date: '2022-01-31'
slug: []
categories:
  - tidytext
  - R
  - dataviz
tags:
  - tidytext
  - R Markdown
---

## Getting to Yes

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning=FALSE)
```


Let's have a brief look at `Getting to Yes`.

## What are the most common words?

```{r textP1, message=FALSE}
library(tidyverse)
library(tidytext)
library(wordcloud)
load("data/SharedGTY.RData")
GTY.WM <- Getting.To.Yes.TDF %>% 
    unnest_tokens(word, text)
tidy_book <- GTY.WM %>%
    anti_join(stop_words)
# The barplot
tidy_book %>%
   count(word, sort = TRUE) %>%
   filter(n > 50) %>%
   mutate(word = reorder(word, n)) %>%
   ggplot(aes(word, n)) +
   geom_col() +
   xlab(NULL) +
   coord_flip()
```

## A Wordcloud?

```{r}
# Make the wordcloud
tidy_book %>%
   count(word) %>%
   with(wordcloud(word, n, max.words = 100))
# Stems in lieu of words
```

## Networks of Words

```{r}
# Networks of words
library(igraph)
library(ggraph)
library(widyr)
count_bigrams <- function(dataset) {
  dataset %>%
    unnest_tokens(bigram, text, token = "ngrams", n = 2) %>%
    separate(bigram, c("word1", "word2"), sep = " ") %>%
    filter(!word1 %in% stop_words$word,
           !word2 %in% stop_words$word) %>%
    count(word1, word2, sort = TRUE)
}
word_cooccurences <- count_bigrams(Getting.To.Yes.TDF)
set.seed(2016)
word_cooccurences %>%
  filter(n >= 10) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = n, edge_width = n)) +
  geom_node_point(color = "plum4", size = 5) +
  geom_node_text(aes(label = name), vjust = 1.8) +
  ggtitle(expression(paste("Word Network in", 
                           italic("Getting to Yes")))) +
  theme_void()
```

Other ways to plot them.

```{r, message=FALSE}
## More complicated breaks: pairs
GTY.PM <- Getting.To.Yes.TDF %>% 
  unnest_tokens(ngram, text, token = "ngrams", n = 2)
bigrams_separated <- GTY.PM %>%
  separate(ngram, c("word1", "word2"), sep = " ")

bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

# new bigram counts:
bigram_counts <- bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)

bigrams_united <- bigrams_filtered %>%
  unite(bigram, word1, word2, sep = " ")

my.df <- data.frame(table(bigrams_united$bigram))
my.df <- my.df[order(my.df$Freq, decreasing=TRUE),]
my.df <- my.df[c(2:100),]
head(my.df)

bigram_counts
library(wordcloud2)
wordcloud2(my.df, color="random-light", backgroundColor = "black", size = 0.4)
```